In [1]:
import matplotlib.pyplot as plt
#plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['font.family'] ='NanumGothic'
plt.rcParams['axes.unicode_minus'] =False

In [2]:
import os                        
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
trainset_0717_final.shape

(1127044, 88)

In [4]:
trainset_0717_final = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data_final/trainset_0717_final.csv')

# 지하철 가까운 역 개수 jimi

In [6]:
test_with_subway_infos = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/test_with_subway_infos.csv')

In [7]:
train_with_subway_infos = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/train_with_subway_infos.csv')

In [8]:
df = pd.concat([train_with_subway_infos,test_with_subway_infos], axis=0)

In [9]:
df = df[['좌표X_2','좌표Y_2','5분이하_역_개수','5분초과_10분이하_역_개수','10분초과_15분이하_역_개수','15분초과_20분이하_역_개수']]

In [10]:
df.drop_duplicates(inplace=True)

In [17]:
df.shape # 아파트 개수를 의미한다

(8955, 6)

In [15]:
trainset_0717_final.columns

Index(['Unnamed: 0', '시군구', '번지', '본번', '부번', '아파트명', '전용면적(㎡)', '계약년월', '계약일',
       '층', '건축년도', '도로명', 'target', 'is_test', '번지주소', '계약년월일', '구', '동',
       '도로명주소', '계약년', '번호', 'k-아파트명', 'k-단지분류(아파트,주상복합등등)', 'kapt도로명주소',
       'k-전체동수', 'k-전체세대수', 'k-건설사(시공사)', '준공일자', 'k-연면적', 'k-주거전용면적',
       'k-관리비부과면적', 'k-전용면적별세대현황(60㎡이하)', 'k-전용면적별세대현황(60㎡~85㎡이하)',
       'k-85㎡~135㎡이하', '주차대수', '입주유형', '단지명', '지번주소_y', '동수_x', '합계 세대수',
       '분양 세대수', '임대 세대수', '토지 면적(㎡)', '합계 동수', '서울특별시_부동산소비심리지수', '미분양_구',
       '국고채-회사채', '생산자물가지수', '소비자물가지수', '서울특별시_가계대출', '서울특별시_주택담보대출',
       '서울특별시_주택매매거래량', '서울특별시_아파트매매거래량', '전국매매가격지수', '전국전세가격지수',
       '서울특별시_주택인허가실적', '서울특별시_주택착공실적', '서울특별시_주택준공실적', '서울특별시_주택미분양',
       '미분양_서울특별시', '지번주소', '공시가격기반단지명', '동수_y', '세대수', '사용승인일자', '소형학원수',
       '중형학원수', '대형학원수', '종합학원수', '입시학원수', '외국어학원수', '예체능학원수', '독서실수', '정보학원수',
       '특수교육학원수', '직업기술학원수', '기타학원수', '모든학원수', 'brand', 'lower_outliers',
       'upper_outliers', '강남여부', '가격높은동', '재건축예상', '미분양_이동평균', '미분양_3개월대비',
       '좌표X_2', '좌표Y_2'],
      dtype='object')

In [14]:
trainset_0717_final.rename(columns={'좌표X_2_y':'좌표X_2', '좌표Y_2_y':'좌표Y_2'}, inplace=True)

In [16]:
trainset_0717_final.drop(columns=['Unnamed: 0'], inplace=True)

In [18]:
df2 = pd.merge(trainset_0717_final, df, left_on=['좌표X_2', '좌표Y_2'], right_on=['좌표X_2','좌표Y_2'], how='left')

In [19]:
df2.shape

(1127044, 91)

In [20]:
trainset_0717_final = df2.copy()

# 버스 역 가까운 개수 jimi

In [21]:
train_with_bus_infos = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/train_with_bus_infos.csv')

In [22]:
test_with_bus_infos = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/test_with_bus_infos.csv')

In [46]:
df = pd.concat([train_with_bus_infos, test_with_bus_infos], axis=0)

In [24]:
df.head(1)

,좌표X_2,좌표Y_2,1번째_가까운_버스정류장_이름,1번째_가까운_버스정류장_거리,1번째_가까운_버스정류장_도보시간,2번째_가까운_버스정류장_이름,2번째_가까운_버스정류장_거리,2번째_가까운_버스정류장_도보시간,3번째_가까운_버스정류장_이름,3번째_가까운_버스정류장_거리,3번째_가까운_버스정류장_도보시간,5분이하_버스정류장_개수,5분초과_10분이하_버스정류장_개수,10분초과_15분이하_버스정류장_개수
0,127.056859,37.476276,23445_개포우성아파트,94.274521,1.414118,23433_개포우성6차아파트,108.73838,1.631076,23338_개포파크빌리지,142.59379,2.138907,9,16,32

In [47]:
df = df[['좌표X_2','좌표Y_2','5분이하_버스정류장_개수','5분초과_10분이하_버스정류장_개수','10분초과_15분이하_버스정류장_개수']]

In [48]:
df.drop_duplicates(inplace=True)

In [28]:
df.shape

(8955, 5)

In [ ]:
trainset_0717_final[trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12']

In [55]:
df[(df['좌표X_2']=='127.06095')&(df['좌표Y_2']=='37.455551')]

Empty DataFrame
Columns: [좌표X_2, 좌표Y_2, 5분이하_버스정류장_개수, 5분초과_10분이하_버스정류장_개수, 10분초과_15분이하_버스정류장_개수]
Index: []

In [30]:
df2 = pd.merge(trainset_0717_final, df, left_on=['좌표X_2', '좌표Y_2'], right_on=['좌표X_2','좌표Y_2'], how='left')

In [31]:
df2.shape

(1127044, 94)

In [32]:
trainset_0717_final = df2.copy()

# 초품아 재명

In [33]:
elemSchool_with_XY = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/elemSchool_with_XY.csv')

In [34]:
elemSchool_with_XY.head(1)

        좌표X_2      좌표Y_2 최단거리초등학교명  최단거리초등학교Km
0  127.056859  37.476276  서울포이초등학교    0.385832

In [35]:
df = pd.merge(trainset_0717_final, elemSchool_with_XY, on=['좌표X_2','좌표Y_2'], how='left')

In [36]:
df.shape

(1127044, 96)

In [37]:
trainset_0717_final= df.copy()

In [38]:
df.to_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data_final/trainset_0717_final.csv')

In [121]:
trainset_0717_final = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data_final/trainset_0717_final.csv')

# 결측치 확인

In [142]:
import pandas as pd

# 결측치 갯수
missing_counts = trainset_0717_final.isna().sum()

# 결측치 비율
missing_ratios = trainset_0717_final.isna().mean() * 100

# 결과를 데이터프레임으로 결합
missing_summary = pd.DataFrame({
    'Missing Count': missing_counts,
    'Missing Ratio (%)': missing_ratios
})

In [143]:
pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',None) 
missing_summary

                        Missing Count  Missing Ratio (%)
Unnamed: 0                          0           0.000000
시군구                                 0           0.000000
번지                                227           0.020141
본번                                 75           0.006655
부번                                 75           0.006655
아파트명                             2136           0.189522
전용면적(㎡)                             0           0.000000
계약년월                                0           0.000000
계약일                                 0           0.000000
층                                   0           0.000000
건축년도                                0           0.000000
도로명                                 0           0.000000
target                           9272           0.822683
is_test                             0           0.000000
번지주소                              227           0.020141
계약년월일                               0           0.000000
구                                   0           0.000000
동                                   0           0.000000
도로명주소                               0           0.000000
계약년                                 0           0.000000
번호                             262365          23.279038
k-아파트명                         262365          23.279038
k-단지분류(아파트,주상복합등등)             262365          23.279038
kapt도로명주소                      262365          23.279038
k-전체동수                         262365          23.279038
k-전체세대수                        262365          23.279038
k-건설사(시공사)                     262815          23.318965
준공일자                           262365          23.279038
k-연면적                          262365          23.279038
k-주거전용면적                       262426          23.284450
k-관리비부과면적                      262365          23.279038
k-전용면적별세대현황(60㎡이하)             262426          23.284450
k-전용면적별세대현황(60㎡~85㎡이하)         262426          23.284450
k-85㎡~135㎡이하                   262426          23.284450
주차대수                           265232          23.533420
입주유형                           297600          26.405358
단지명                            297600          26.405358
지번주소_y                         297600          26.405358
동수_x                           297600          26.405358
합계 세대수                         297600          26.405358
분양 세대수                         297822          26.425055
임대 세대수                        1062401          94.264377
토지 면적(㎡)                       391978          34.779299
합계 동수                          297600          26.405358
서울특별시_부동산소비심리지수                263308          23.362708
미분양_구                            9982           0.885680
국고채-회사채                             0           0.000000
생산자물가지수                             0           0.000000
소비자물가지수                             0           0.000000
서울특별시_가계대출                      53417           4.739567
서울특별시_주택담보대출                    53417           4.739567
서울특별시_주택매매거래량                       0           0.000000
서울특별시_아파트매매거래량                      0           0.000000
전국매매가격지수                            0           0.000000
전국전세가격지수                            0           0.000000
서울특별시_주택인허가실적                       0           0.000000
서울특별시_주택착공실적                   233242          20.695022
서울특별시_주택준공실적                   208393          18.490228
서울특별시_주택미분양                         0           0.000000
미분양_서울특별시                           0           0.000000
지번주소                                0           0.000000
공시가격기반단지명                      343822          30.506529
동수_y                           343822          30.506529
세대수                            343822          30.506529
사용승인일자                         343822          30.506529
소형학원수                          343822          30.506529
중형학원수                          343822          30.506529
대형학원수                          343822          30.506529
종합학원수                          343822          30.506529
입시학원수                          343822          30.506529
외국어학원수                         343822          30.506529
예체능학원수                         343822          30.506529
독서실수                           343822          30.506529
정보학원수                          343822          30.506529
특수교육학원수                        343822          30.506529
직업기술학원수                        343822          30.506529
기타학원수                          343822          30.506529
모든학원수                               0           0.000000
brand                               0           0.000000
lower_outliers                      0           0.000000
upper_outliers                      0           0.000000
강남여부                                0           0.000000
가격높은동                               0           0.000000
재건축예상                               0           0.000000
미분양_이동평균                         9920           0.880179
미분양_3개월대비                           0           0.000000
좌표X_2                               0           0.000000
좌표Y_2                               0           0.000000
5분이하_역_개수                           0           0.000000
5분초과_10분이하_역_개수                     0           0.000000
10분초과_15분이하_역_개수                    0           0.000000
15분초과_20분이하_역_개수                    0           0.000000
5분이하_버스정류장_개수                       0           0.000000
5분초과_10분이하_버스정류장_개수                 0           0.000000
10분초과_15분이하_버스정류장_개수                0           0.000000
최단거리초등학교명                         227           0.020141
최단거리초등학교Km                        227           0.020141

서울특별시 서초구 헌릉로8길 10-12   10	23	12	12
서울특별시 서초구 헌릉로8길 45   19	6	18	11

In [124]:
filtered = trainset_0717_final[trainset_0717_final['5분이하_버스정류장_개수'].isna()==True][['아파트명','도로명주소','지번주소','건축년도','5분이하_버스정류장_개수']].drop_duplicates()

In [125]:
filtered

,아파트명,도로명주소,지번주소,건축년도,5분이하_버스정류장_개수
514613,힐스테이트 서초 젠트리스,서울특별시 서초구 헌릉로8길 10-12,서울특별시 서초구 신원동 557,2014,NaN
547480,서초포레스타2단지,서울특별시 서초구 헌릉로8길 45,서울특별시 서초구 내곡동 384,2015,NaN

In [126]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'5분이하_버스정류장_개수'] =10

In [127]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'5분초과_10분이하_버스정류장_개수'] =23

In [128]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'10분초과_15분이하_버스정류장_개수'] =12

In [131]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'5분이하_버스정류장_개수'] =19

In [130]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'5분초과_10분이하_버스정류장_개수'] =6

In [129]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'10분초과_15분이하_버스정류장_개수'] =18

In [114]:
filtered

,아파트명,도로명주소,지번주소,건축년도,5분이하_버스정류장_개수
514613,힐스테이트 서초 젠트리스,서울특별시 서초구 헌릉로8길 10-12,서울특별시 서초구 신원동 557,2014,NaN
547480,서초포레스타2단지,서울특별시 서초구 헌릉로8길 45,서울특별시 서초구 내곡동 384,2015,NaN

In [60]:
df.columns

Index(['좌표X_2', '좌표Y_2', '5분이하_버스정류장_개수', '5분초과_10분이하_버스정류장_개수',
       '10분초과_15분이하_버스정류장_개수'],
      dtype='object')

5분이하_역_개수	5분초과_10분이하_역_개수	10분초과_15분이하_역_개수	15분초과_20분이하_역_개수 서울특별시 서초구 헌릉로8길 45

In [134]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'5분이하_역_개수'] = 0

In [135]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'5분초과_10분이하_역_개수'] = 0

In [136]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'10분초과_15분이하_역_개수'] = 0

In [137]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'15분초과_20분이하_역_개수'] =1

In [138]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'5분이하_역_개수'] = 0

In [139]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'5분초과_10분이하_역_개수'] = 0

In [140]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'10분초과_15분이하_역_개수'] = 0

In [141]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'15분초과_20분이하_역_개수'] =1

In [63]:
df[(df['좌표X_2']==127.0609537)&(df['좌표Y_2']==37.455551)]

Empty DataFrame
Columns: [좌표X_2, 좌표Y_2, 5분이하_버스정류장_개수, 5분초과_10분이하_버스정류장_개수, 10분초과_15분이하_버스정류장_개수]
Index: []

In [ ]:
import pandas as pd
import numpy as np
from scipy.spatial import cKDTree

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # 지구의 반경 (km)
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    distance = R * c
    return distance * 1000  # 미터 단위로 변환

def walking_time(distance):
    return distance / (4000/60)  # 4km/h의 걷는 속도 가정

def add_subway_features(apartment_df, subway_df):
    apartment_coords = apartment_df[['좌표Y_2', '좌표X_2']].values
    station_coords = subway_df[['위도', '경도']].values

    # 가장 가까운 3개의 역 찾기
    tree = cKDTree(station_coords)
    distances, indices = tree.query(apartment_coords, k=3)

    for i in range(3):
        apartment_df[f'{i+1}번째_가까운_역_이름'] = subway_df.loc[indices[:, i], '역사명'].values
        apartment_df[f'{i+1}번째_가까운_역_호선'] = subway_df.loc[indices[:, i], '호선'].values
        apartment_df[f'{i+1}번째_가까운_역_거리'] = np.array([haversine_distance(ac[0], ac[1], station_coords[idx][0], station_coords[idx][1]) 
                                                   for ac, idx in zip(apartment_coords, indices[:, i])])
        apartment_df[f'{i+1}번째_가까운_역_도보시간'] = walking_time(apartment_df[f'{i+1}번째_가까운_역_거리'])

    # 시간대별 역 개수 계산
    def count_stations_in_time_range(min_time, max_time):
        min_dist = min_time * (4000/60)
        max_dist = max_time * (4000/60)
        return np.array([np.sum((min_dist < haversine_distance(c[0], c[1], station_coords[:, 0], station_coords[:, 1])) & 
                                (haversine_distance(c[0], c[1], station_coords[:, 0], station_coords[:, 1]) <= max_dist)) 
                         for c in apartment_coords])

    apartment_df['5분이하_역_개수'] = count_stations_in_time_range(0, 5)
    apartment_df['5분초과_10분이하_역_개수'] = count_stations_in_time_range(5, 10)
    apartment_df['10분초과_15분이하_역_개수'] = count_stations_in_time_range(10, 15)
    apartment_df['15분초과_20분이하_역_개수'] = count_stations_in_time_range(15, 20)

    return apartment_df

merged_apartment_df = add_subway_features(apartment_df, subway_df)

In [70]:
test_with_bus_infos=pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/test_with_bus_infos.csv')

In [82]:
test_with_bus_infos.head(1)

,좌표X_2,좌표Y_2,1번째_가까운_버스정류장_이름,1번째_가까운_버스정류장_거리,1번째_가까운_버스정류장_도보시간,2번째_가까운_버스정류장_이름,2번째_가까운_버스정류장_거리,2번째_가까운_버스정류장_도보시간,3번째_가까운_버스정류장_이름,3번째_가까운_버스정류장_거리,3번째_가까운_버스정류장_도보시간,5분이하_버스정류장_개수,5분초과_10분이하_버스정류장_개수,10분초과_15분이하_버스정류장_개수
0,127.056859,37.476276,23445_개포우성아파트,94.274521,1.414118,23433_개포우성6차아파트,108.73838,1.631076,23338_개포파크빌리지,142.59379,2.138907,9,16,32

In [ ]:
import pandas as pd

# 데이터 생성
data = {
    '도로명주소': ['서울특별시 서초구 헌릉로8길 10-12', '서울특별시 서초구 헌릉로8길 45'],
    '지번주소': ['서울특별시 서초구 신원동 557', '서울특별시 서초구 내곡동 384'],
    '좌표X_2': [127.057654, 127.06095],
    '좌표Y_2': [37.456285, 37.455551]
}

# 데이터프레임 생성
missing = pd.DataFrame(data)

In [67]:
missing

                   도로명주소               지번주소       좌표X_2      좌표Y_2
0  서울특별시 서초구 헌릉로8길 10-12  서울특별시 서초구 신원동 557  127.057654  37.456285
1     서울특별시 서초구 헌릉로8길 45  서울특별시 서초구 내곡동 384  127.060950  37.455551

In [68]:
subway_feature = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/subway_feature.csv')

In [74]:
missing_for_station = pd.merge(missing, subway_feature, how='cross')

In [76]:
missing_for_station.head(3)

,도로명주소,지번주소,좌표X_2,좌표Y_2,역사_ID,역사명,호선,위도,경도
0,서울특별시 서초구 헌릉로8길 10-12,서울특별시 서초구 신원동 557,127.057654,37.456285,9996,미사,5호선,37.560927,127.193877
1,서울특별시 서초구 헌릉로8길 10-12,서울특별시 서초구 신원동 557,127.057654,37.456285,9995,강일,5호선,37.557490,127.175930
2,서울특별시 서초구 헌릉로8길 10-12,서울특별시 서초구 신원동 557,127.057654,37.456285,4929,김포공항,김포골드라인,37.562360,126.801868

In [ ]:
import pandas as pd
import numpy as np
from scipy.spatial import cKDTree

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # 지구의 반경 (km)
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    distance = R * c
    return distance * 1000  # 미터 단위로 변환

def walking_time(distance):
    return distance / (4000/60)  # 4km/h의 걷는 속도 가정

def add_subway_features(apartment_df, subway_df):
    apartment_coords = apartment_df[['좌표Y_2', '좌표X_2']].values
    station_coords = subway_df[['위도', '경도']].values

    # 가장 가까운 3개의 역 찾기
    tree = cKDTree(station_coords)
    distances, indices = tree.query(apartment_coords, k=3)

    for i in range(3):
        apartment_df[f'{i+1}번째_가까운_역_이름'] = subway_df.loc[indices[:, i], '역사명'].values
        apartment_df[f'{i+1}번째_가까운_역_호선'] = subway_df.loc[indices[:, i], '호선'].values
        apartment_df[f'{i+1}번째_가까운_역_거리'] = np.array([haversine_distance(ac[0], ac[1], station_coords[idx][0], station_coords[idx][1]) 
                                                   for ac, idx in zip(apartment_coords, indices[:, i])])
        apartment_df[f'{i+1}번째_가까운_역_도보시간'] = walking_time(apartment_df[f'{i+1}번째_가까운_역_거리'])

    # 시간대별 역 개수 계산
    def count_stations_in_time_range(min_time, max_time):
        min_dist = min_time * (4000/60)
        max_dist = max_time * (4000/60)
        return np.array([np.sum((min_dist < haversine_distance(c[0], c[1], station_coords[:, 0], station_coords[:, 1])) & 
                                (haversine_distance(c[0], c[1], station_coords[:, 0], station_coords[:, 1]) <= max_dist)) 
                         for c in apartment_coords])

    apartment_df['5분이하_역_개수'] = count_stations_in_time_range(0, 5)
    apartment_df['5분초과_10분이하_역_개수'] = count_stations_in_time_range(5, 10)
    apartment_df['10분초과_15분이하_역_개수'] = count_stations_in_time_range(10, 15)
    apartment_df['15분초과_20분이하_역_개수'] = count_stations_in_time_range(15, 20)

    return apartment_df

merged_apartment_df = add_subway_features(missing, subway_feature)

In [102]:
bus_feature = pd.read_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data/bus_feature.csv')

In [109]:
import pandas as pd
import numpy as np
from scipy.spatial import cKDTree

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # 지구의 반경 (km)
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    distance = R * c
    return distance * 1000  # 미터 단위로 변환

def walking_time(distance):
    return distance / (4000/60)  # 4km/h의 걷는 속도 가정

def add_subway_features(apartment_df, subway_df):
    apartment_coords = apartment_df[['좌표Y_2', '좌표X_2']].values
    station_coords = subway_df[['Y좌표', 'X좌표']].values

    # 가장 가까운 3개의 역 찾기
    tree = cKDTree(station_coords)
    distances, indices = tree.query(apartment_coords, k=3)

    for i in range(3):
        apartment_df[f'{i+1}번째_가까운_정류소명'] = subway_df.loc[indices[:, i], '정류소명'].values
        #apartment_df[f'{i+1}번째_가까운_역_호선'] = subway_df.loc[indices[:, i], '호선'].values
        apartment_df[f'{i+1}번째_가까운_정류소_거리'] = np.array([haversine_distance(ac[0], ac[1], station_coords[idx][0], station_coords[idx][1]) 
                                                   for ac, idx in zip(apartment_coords, indices[:, i])])
        apartment_df[f'{i+1}번째_가까운_정류소_도보시간'] = walking_time(apartment_df[f'{i+1}번째_가까운_역_거리'])

    # 시간대별 역 개수 계산
    def count_stations_in_time_range(min_time, max_time):
        min_dist = min_time * (4000/60)
        max_dist = max_time * (4000/60)
        return np.array([np.sum((min_dist < haversine_distance(c[0], c[1], station_coords[:, 0], station_coords[:, 1])) & 
                                (haversine_distance(c[0], c[1], station_coords[:, 0], station_coords[:, 1]) <= max_dist)) 
                         for c in apartment_coords])

    apartment_df['5분이하_정류소_개수'] = count_stations_in_time_range(0, 5)
    apartment_df['5분초과_10분이하_정류소_개수'] = count_stations_in_time_range(5, 10)
    apartment_df['10분초과_15분이하_정류소_개수'] = count_stations_in_time_range(10, 15)
    apartment_df['15분초과_20분이하_정류소_개수'] = count_stations_in_time_range(15, 20)

    return apartment_df

merged_apartment_df = add_subway_features(missing, bus_feature)

서울특별시 서초구 헌릉로8길 10-12 10	23	12	12
서울특별시 서초구 헌릉로8길 45 19	6	18	11

In [110]:
merged_apartment_df

,도로명주소,지번주소,좌표X_2,좌표Y_2,1번째_가까운_역_이름,1번째_가까운_역_호선,1번째_가까운_역_거리,1번째_가까운_역_도보시간,2번째_가까운_역_이름,2번째_가까운_역_호선,2번째_가까운_역_거리,2번째_가까운_역_도보시간,3번째_가까운_역_이름,3번째_가까운_역_호선,3번째_가까운_역_거리,3번째_가까운_역_도보시간,5분이하_역_개수,5분초과_10분이하_역_개수,10분초과_15분이하_역_개수,15분초과_20분이하_역_개수,1번째_가까운_정류소명,1번째_가까운_정류소_거리,1번째_가까운_정류소_도보시간,2번째_가까운_정류소명,2번째_가까운_정류소_거리,2번째_가까운_정류소_도보시간,3번째_가까운_정류소명,3번째_가까운_정류소_거리,3번째_가까운_정류소_도보시간,5분이하_정류소_개수,5분초과_10분이하_정류소_개수,10분초과_15분이하_정류소_개수,15분초과_20분이하_정류소_개수
0,서울특별시 서초구 헌릉로8길 10-12,서울특별시 서초구 신원동 557,127.057654,37.456285,청계산입구,신분당선,1024.160335,15.362405,양재시민의숲(매헌),신분당선,2283.724024,34.255860,구룡,분당선,3399.105383,50.986581,0,0,0,1,탑성마을.서초포레스타입구,171.561579,15.362405,탑성마을.서초포레스타입구,187.588485,34.255860,서초포레스타3단지정문,176.592640,50.986581,10,23,12,12
1,서울특별시 서초구 헌릉로8길 45,서울특별시 서초구 내곡동 384,127.060950,37.455551,청계산입구,신분당선,1038.142238,15.572134,양재시민의숲(매헌),신분당선,2558.077919,38.371169,구룡,분당선,3483.971342,52.259570,0,0,0,1,언남초등학교,134.642540,15.572134,언남초등학교,144.358927,38.371169,서초포레스타3단지정문,126.095576,52.259570,19,6,18,11

In [144]:
trainset_0717_final.to_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data_final/trainset_0717_final_missing.csv')

# elemschool 2컬럼 업데이트

In [150]:
import pandas as pd

# 결측치 갯수
missing_counts = trainset_0717_final.isna().sum()

# 결측치 비율
missing_ratios = trainset_0717_final.isna().mean() * 100

# 결과를 데이터프레임으로 결합
missing_summary = pd.DataFrame({
    'Missing Count': missing_counts,
    'Missing Ratio (%)': missing_ratios
})

In [151]:
pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',None) 
missing_summary

                        Missing Count  Missing Ratio (%)
Unnamed: 0                          0           0.000000
시군구                                 0           0.000000
번지                                227           0.020141
본번                                 75           0.006655
부번                                 75           0.006655
아파트명                             2136           0.189522
전용면적(㎡)                             0           0.000000
계약년월                                0           0.000000
계약일                                 0           0.000000
층                                   0           0.000000
건축년도                                0           0.000000
도로명                                 0           0.000000
target                           9272           0.822683
is_test                             0           0.000000
번지주소                              227           0.020141
계약년월일                               0           0.000000
구                                   0           0.000000
동                                   0           0.000000
도로명주소                               0           0.000000
계약년                                 0           0.000000
번호                             262365          23.279038
k-아파트명                         262365          23.279038
k-단지분류(아파트,주상복합등등)             262365          23.279038
kapt도로명주소                      262365          23.279038
k-전체동수                         262365          23.279038
k-전체세대수                        262365          23.279038
k-건설사(시공사)                     262815          23.318965
준공일자                           262365          23.279038
k-연면적                          262365          23.279038
k-주거전용면적                       262426          23.284450
k-관리비부과면적                      262365          23.279038
k-전용면적별세대현황(60㎡이하)             262426          23.284450
k-전용면적별세대현황(60㎡~85㎡이하)         262426          23.284450
k-85㎡~135㎡이하                   262426          23.284450
주차대수                           265232          23.533420
입주유형                           297600          26.405358
단지명                            297600          26.405358
지번주소_y                         297600          26.405358
동수_x                           297600          26.405358
합계 세대수                         297600          26.405358
분양 세대수                         297822          26.425055
임대 세대수                        1062401          94.264377
토지 면적(㎡)                       391978          34.779299
합계 동수                          297600          26.405358
서울특별시_부동산소비심리지수                263308          23.362708
미분양_구                            9982           0.885680
국고채-회사채                             0           0.000000
생산자물가지수                             0           0.000000
소비자물가지수                             0           0.000000
서울특별시_가계대출                      53417           4.739567
서울특별시_주택담보대출                    53417           4.739567
서울특별시_주택매매거래량                       0           0.000000
서울특별시_아파트매매거래량                      0           0.000000
전국매매가격지수                            0           0.000000
전국전세가격지수                            0           0.000000
서울특별시_주택인허가실적                       0           0.000000
서울특별시_주택착공실적                   233242          20.695022
서울특별시_주택준공실적                   208393          18.490228
서울특별시_주택미분양                         0           0.000000
미분양_서울특별시                           0           0.000000
지번주소                                0           0.000000
공시가격기반단지명                      343822          30.506529
동수_y                           343822          30.506529
세대수                            343822          30.506529
사용승인일자                         343822          30.506529
소형학원수                          343822          30.506529
중형학원수                          343822          30.506529
대형학원수                          343822          30.506529
종합학원수                          343822          30.506529
입시학원수                          343822          30.506529
외국어학원수                         343822          30.506529
예체능학원수                         343822          30.506529
독서실수                           343822          30.506529
정보학원수                          343822          30.506529
특수교육학원수                        343822          30.506529
직업기술학원수                        343822          30.506529
기타학원수                          343822          30.506529
모든학원수                               0           0.000000
brand                               0           0.000000
lower_outliers                      0           0.000000
upper_outliers                      0           0.000000
강남여부                                0           0.000000
가격높은동                               0           0.000000
재건축예상                               0           0.000000
미분양_이동평균                         9920           0.880179
미분양_3개월대비                           0           0.000000
좌표X_2                               0           0.000000
좌표Y_2                               0           0.000000
5분이하_역_개수                           0           0.000000
5분초과_10분이하_역_개수                     0           0.000000
10분초과_15분이하_역_개수                    0           0.000000
15분초과_20분이하_역_개수                    0           0.000000
5분이하_버스정류장_개수                       0           0.000000
5분초과_10분이하_버스정류장_개수                 0           0.000000
10분초과_15분이하_버스정류장_개수                0           0.000000
최단거리초등학교명                           0           0.000000
최단거리초등학교Km                          0           0.000000

In [145]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'최단거리초등학교명'] ='서울언남초등학교'

In [147]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 45'),'최단거리초등학교Km'] =0.16578385656878478

In [148]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'최단거리초등학교명'] ='서울언남초등학교'

In [149]:
trainset_0717_final.loc[(trainset_0717_final['도로명주소']=='서울특별시 서초구 헌릉로8길 10-12'),'최단거리초등학교Km'] =0.41284121062228589

In [152]:
trainset_0717_final.to_csv(r'/data/ephemeral/home/yjl/upstage-ml-regression-ml5/data_final/trainset_0717_final.csv')