In [22]:
# visualization
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import re
fe = fm.FontEntry(fname=r'font/NanumGothic.otf', name='NanumBarunGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams.update({'font.size': 10, 'font.family': 'NanumBarunGothic'})
plt.rc('font', family='NanumBarunGothic')
import seaborn as sns

# utils
import pandas as pd
import numpy as np
from tqdm import tqdm
import pickle
import warnings;warnings.filterwarnings('ignore')


pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [23]:
# 필요한 데이터를 load 하겠습니다. 경로는 환경에 맞게 지정해주면 됩니다.
data_path = '../data/'
# test_path  = ''
data = pd.read_csv(f'{data_path}240717_train.csv')
# dt_test = pd.read_csv(test_path)
b_name = pd.read_csv(f'{data_path}b_name.csv')

In [24]:
df = data.copy()

In [25]:
df = pd.concat([df, b_name], axis=1)
# df.to_csv(f'{train_path}240717_2.csv', index=False)

In [26]:
col_list = ['전용면적(㎡)', 
 '층', 
 '건축년도', 
'target', 
'is_test', 
'계약년월일',
'k-전용면적별세대현황(60㎡이하)',
'k-전용면적별세대현황(60㎡~85㎡이하)', 
'k-85㎡~135㎡이하', 
'k-135㎡초과', 
'주차대수', 
'Nearest_Bus_Station_Name', 
'Nearest_Subway_Station_Name',
 '5층 동수', 
 '5층 세대수', 
 '6~10층 동수', 
 '6~10층 세대수', 
 '11~15층 동수', 
 '11~15층 세대수', 
 '16~20층 동수', 
 '16~20층 세대수',
 '21층이상 동수', 
 '21층이상 세대수', 
 '시점',
 '국고채', 
 '회사채', 
 '국고채-회사채', 
 '생산자물가지수', 
 '소비자물가지수', 
 '서울특별시_가계대출',
 '서울특별시_주택담보대출',
  '서울특별시_주택매매거래량', 
  '서울특별시_아파트매매거래량', 
  '전국매매가격지수', 
  '전국전세가격지수',
 '세대수', 
 '좌표X_jm', 
 '좌표Y_jm',
 '번지주소_2', 
 '도로명_fill', 
 '최단거리초등학교명', 
 '최단거리초등학교Km',
 '좌표X_2', 
 '좌표Y_2', 
 '1번째_가까운_역_이름', 
 '1번째_가까운_역_호선', 
 '1번째_가까운_역_거리', 
 '1번째_가까운_역_도보시간', 
 '2번째_가까운_역_이름', 
 '2번째_가까운_역_호선', 
 '2번째_가까운_역_거리', 
 '2번째_가까운_역_도보시간', 
 '3번째_가까운_역_이름', 
 '3번째_가까운_역_호선', 
 '3번째_가까운_역_거리', 
 '3번째_가까운_역_도보시간', 
 '5분이하_역_개수', 
 '5분초과_10분이하_역_개수', 
 '10분초과_15분이하_역_개수',
'15분초과_20분이하_역_개수', 
'건물명']

In [27]:
df = df[col_list]

In [28]:
df = df.drop(columns=['서울특별시_가계대출','서울특별시_주택담보대출'])

In [29]:
df.head(1)

,전용면적(㎡),층,건축년도,target,is_test,계약년월일,k-전용면적별세대현황(60㎡이하),k-전용면적별세대현황(60㎡~85㎡이하),k-85㎡~135㎡이하,k-135㎡초과,주차대수,Nearest_Bus_Station_Name,Nearest_Subway_Station_Name,5층 동수,5층 세대수,6~10층 동수,6~10층 세대수,11~15층 동수,11~15층 세대수,16~20층 동수,16~20층 세대수,21층이상 동수,21층이상 세대수,시점,국고채,회사채,국고채-회사채,생산자물가지수,소비자물가지수,서울특별시_주택매매거래량,서울특별시_아파트매매거래량,전국매매가격지수,전국전세가격지수,세대수,좌표X_jm,좌표Y_jm,번지주소_2,도로명_fill,최단거리초등학교명,최단거리초등학교Km,좌표X_2,좌표Y_2,1번째_가까운_역_이름,1번째_가까운_역_호선,1번째_가까운_역_거리,1번째_가까운_역_도보시간,2번째_가까운_역_이름,2번째_가까운_역_호선,2번째_가까운_역_거리,2번째_가까운_역_도보시간,3번째_가까운_역_이름,3번째_가까운_역_호선,3번째_가까운_역_거리,3번째_가까운_역_도보시간,5분이하_역_개수,5분초과_10분이하_역_개수,10분초과_15분이하_역_개수,15분초과_20분이하_역_개수,건물명
0,79.97,3,1987,124000.0,0,2017-12-08,20.0,250.0,0.0,NaN,262.0,개포우성아파트,구룡,8.0,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201712,2.1,2.649,0.549,99.09,97.698,13740.0,8484.0,87.701,93.042,270.0,127.056859,37.476276,서울특별시 강남구 개포동 658-1,서울특별시 강남구 언주로 3,서울포이초등학교,0.385832,127.056859,37.476276,구룡,분당선,1187.672025,17.81508,매봉,3호선,1483.43809,22.251571,도곡,3호선,1633.265245,24.498979,0,0,0,1,개포6차우성

In [30]:
df.loc[df['k-전용면적별세대현황(60㎡이하)'].isna(), 'k-전용면적별세대현황(60㎡이하)'] = 0
df.loc[df['k-전용면적별세대현황(60㎡~85㎡이하)'].isna(), 'k-전용면적별세대현황(60㎡~85㎡이하)'] = 0
df.loc[df['k-85㎡~135㎡이하'].isna(), 'k-85㎡~135㎡이하'] = 0
df.loc[df['k-135㎡초과'].isna(), 'k-135㎡초과'] = 0
df.loc[df['주차대수'].isna(), '주차대수'] = 0
df.loc[df['5층 동수'].isna(), '5층 동수'] = 0
df.loc[df['5층 세대수'].isna(), '5층 세대수'] = 0
df.loc[df['6~10층 동수'].isna(), '6~10층 동수'] = 0
df.loc[df['6~10층 세대수'].isna(), '6~10층 세대수'] = 0
df.loc[df['11~15층 동수'].isna(), '11~15층 동수'] = 0
df.loc[df['11~15층 세대수'].isna(), '11~15층 세대수'] = 0
df.loc[df['16~20층 동수'].isna(), '16~20층 동수'] = 0
df.loc[df['16~20층 세대수'].isna(), '16~20층 세대수'] = 0
df.loc[df['21층이상 동수'].isna(), '21층이상 동수'] = 0
df.loc[df['21층이상 세대수'].isna(), '21층이상 세대수'] = 0

In [31]:
# '도로명_fill' 칼럼에서 결측치를 '번지주소_2'의 값으로 채우기
df.loc[df['도로명_fill'].isna(), '도로명_fill'] = df['번지주소_2']

In [32]:
df['세대수_sum'] = df['k-전용면적별세대현황(60㎡이하)'] + df['k-전용면적별세대현황(60㎡~85㎡이하)'] + \
                    df['k-85㎡~135㎡이하'] + df['k-135㎡초과']

In [33]:
df['세대수_sum_2'] = df['5층 세대수'] + df['6~10층 세대수'] + \
                    df['11~15층 세대수'] + df['16~20층 세대수'] + df['21층이상 세대수']

In [34]:
test = df[['세대수', '번지주소_2', '건물명', '세대수_sum', '세대수_sum_2']].copy()

In [35]:
test[test['세대수'].isnull()].head(3)

    세대수             번지주소_2      건물명  세대수_sum  세대수_sum_2
38  NaN  서울특별시 강남구 개포동 141  개포주공1단지   5040.0        0.0
39  NaN  서울특별시 강남구 개포동 141  개포주공1단지   5040.0        0.0
40  NaN  서울특별시 강남구 개포동 141  개포주공1단지   5040.0        0.0

In [36]:
test.isna().sum()

세대수          344872
번지주소_2            0
건물명               0
세대수_sum           0
세대수_sum_2         0
dtype: int64

In [39]:
test.loc[test['세대수_sum']==0, '세대수_sum'] = np.nan

In [40]:
test.loc[test['세대수_sum_2']==0, '세대수_sum_2'] = np.nan

In [41]:
test.loc[(test['세대수'].isna()), '세대수'] = test.loc[(test['세대수'].isna()), '세대수'].fillna(test['세대수_sum'])

In [42]:
test.loc[(test['세대수'].isna()), '세대수'] = test.loc[(test['세대수'].isna()), '세대수'].fillna(test['세대수_sum_2'])

In [43]:
test.loc[(test['세대수'].isna()) & (df['건물명']=='0'), '세대수'] = 10
test.loc[(test['세대수'].isna()) & (df['건물명']=='1'), '세대수'] = 10

In [44]:
test.isna().sum() # 세대수 344872->124243 ->69748->69701  세대수_sum 266413  세대수_sum_2 298650

세대수           69701
번지주소_2            0
건물명               0
세대수_sum      266413
세대수_sum_2    298650
dtype: int64

In [45]:
test['세대수'] = test['세대수'].fillna(round(test['세대수'].mean())) # mean = 967

In [46]:
df['세대수_수정'] = test['세대수']
df.head(1)

,전용면적(㎡),층,건축년도,target,is_test,계약년월일,k-전용면적별세대현황(60㎡이하),k-전용면적별세대현황(60㎡~85㎡이하),k-85㎡~135㎡이하,k-135㎡초과,주차대수,Nearest_Bus_Station_Name,Nearest_Subway_Station_Name,5층 동수,5층 세대수,6~10층 동수,6~10층 세대수,11~15층 동수,11~15층 세대수,16~20층 동수,16~20층 세대수,21층이상 동수,21층이상 세대수,시점,국고채,회사채,국고채-회사채,생산자물가지수,소비자물가지수,서울특별시_주택매매거래량,서울특별시_아파트매매거래량,전국매매가격지수,전국전세가격지수,세대수,좌표X_jm,좌표Y_jm,번지주소_2,도로명_fill,최단거리초등학교명,최단거리초등학교Km,좌표X_2,좌표Y_2,1번째_가까운_역_이름,1번째_가까운_역_호선,1번째_가까운_역_거리,1번째_가까운_역_도보시간,2번째_가까운_역_이름,2번째_가까운_역_호선,2번째_가까운_역_거리,2번째_가까운_역_도보시간,3번째_가까운_역_이름,3번째_가까운_역_호선,3번째_가까운_역_거리,3번째_가까운_역_도보시간,5분이하_역_개수,5분초과_10분이하_역_개수,10분초과_15분이하_역_개수,15분초과_20분이하_역_개수,건물명,세대수_sum,세대수_sum_2,세대수_수정
0,79.97,3,1987,124000.0,0,2017-12-08,20.0,250.0,0.0,0.0,262.0,개포우성아파트,구룡,8.0,270.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,201712,2.1,2.649,0.549,99.09,97.698,13740.0,8484.0,87.701,93.042,270.0,127.056859,37.476276,서울특별시 강남구 개포동 658-1,서울특별시 강남구 언주로 3,서울포이초등학교,0.385832,127.056859,37.476276,구룡,분당선,1187.672025,17.81508,매봉,3호선,1483.43809,22.251571,도곡,3호선,1633.265245,24.498979,0,0,0,1,개포6차우성,270.0,270.0,270.0

In [47]:
# 필요없는 세대수 열들 삭제하기
df.drop(columns=['세대수', '세대수_sum', '세대수_sum_2'], inplace=True)

In [ ]:
# df.to_csv(f'{train_path}ing_not_null.csv', index=False)